# This is a basic workflow to help you get started with Actions
#this  dont work on this repo so imajust remove the  auto thing
name: Windows Build CI

# Controls when the workflow will run
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.3
          
      - name: Cache haxelib path
        uses: actions/cache@v2
        with:
          path: |
            %HAXELIB_ROOT%
          key: ${{ runner.os }}
          
      - name: Setup Windows SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1
                
          

      # Runs a set of commands using the runners shell
      - name: script run line haha
        run: |
          mkdir -p "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl --quiet
          haxelib install flixel 4.9.0 --quiet
          haxelib install hxcpp --quiet
          haxelib run lime setup
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install hscript --quiet
          haxelib git faxe https://github.com/uhrobots/faxe --quiet
          haxelib git polymod https://github.com/MasterEric/polymod.git --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git extension-webm-2 https://github.com/jigsaw-4277821/extension-webm --quiet
          haxelib git linc_luajit https://github.com/Daninnocent/linc_luajit.git --quiet
          haxelib install actuate 
          haxelib install newgrounds
          haxelib install systools
          haxelib list
          
      - name: Build Log
        run: |
          haxelib run lime rebuild extension-webm-2 windows
          haxelib run lime build windows -Dci
          
      - uses: actions/upload-artifact@v2
        with:
          name: Android Build
          path: export/release/windows/bin
